### ISSUE TITLE
The app crashes when I press the button

### ISSUE THREAD

**Issue by Wjxfi** [NimaKhajehpour/MyMood#30]
![ecb404e5-e9ff-4b26-bbe4-9e707a9c0ede.jpg](https://github.com/NimaKhajehpour/MyMood/assets/113500363/b1ee6631-d5bb-46ab-99e5-44b0a8820797)

```
FATAL EXCEPTION: main
Process: com.nima.mymood, PID: 26027
java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:757)
	at java.lang.Integer.parseInt(Integer.java:865)
	at com.nima.mymood.screens.DayGraphScreenKt$DayGraphScreen$1$2.invoke(DayGraphScreen.kt:99)
	at com.nima.mymood.screens.DayGraphScreenKt$DayGraphScreen$1$2.invoke(DayGraphScreen.kt:95)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:149)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at com.nima.mymood.graph.LineGraphKt$LineGraph$2$1$5.invoke(LineGraph.kt:215)
	at com.nima.mymood.graph.LineGraphKt$LineGraph$2$1$5.invoke(LineGraph.kt:214)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at com.nima.mymood.graph.GraphAxesKt.GraphXAxis-FJfuzF0(GraphAxes.kt:125)
	at com.nima.mymood.graph.LineGraphKt$LineGraph$2.invoke(LineGraph.kt:197)
	at com.nima.mymood.graph.LineGraphKt$LineGraph$2.invoke(LineGraph.kt:62)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at com.nima.mymood.graph.LineGraphKt.LineGraph-T042LqI(LineGraph.kt:60)
	at com.nima.mymood.screens.DayGraphScreenKt.DayGraphScreen(DayGraphScreen.kt:68)
	at com.nima.mymood.navigation.MoodNavigationKt$MoodNavigation$1$13.invoke(MoodNavigation.kt:71)
	at com.nima.mymood.navigation.MoodNavigationKt$MoodNavigation$1$13.invoke(MoodNavigation.kt:70)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.navigation.compose.NavHostKt$NavHost$4$2.invoke(NavHost.kt:163)
	at androidx.navigation.compose.NavHostKt$NavHost$4$2.invoke(NavHost.kt:162)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
	at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:65)
	at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:47)
	at androidx.navigation.compose.NavHostKt$NavHost$4.invoke(NavHost.kt:162)
	at androidx.navigation.compose.NavHostKt$NavHost$4.invoke(NavHost.kt:141)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:162)
```

**Comment by NimaKhajehpour** [comment]
Ok i guess i know why it crashes. I will fix the bug. Its because of the effects not having time on them so it cant get them for the graph. Thanks for letting me know.
